[package]
name = "rust-ide"
version = "0.1.0"
authors = ["geoph9 <geoph9@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
cute = "0.3.0"